"use client";
import React from "react";
import styles from "../../styles/OnGrid.module.css";
import Image from "next/image";
import Link from "next/link";
import ServicePageNavigation from "../../components/ServicePageNavigation";

const OnGridSolar: React.FC = () => {
    return (
        <div className={styles.container}>
            <Link href="/" className={styles.backLink} aria-label="Back to Home" title="Back to Home">←</Link>

            {/* Category */}
            <span className={styles.category}>General</span>
            <ServicePageNavigation
                previous={{ href: "/off-grid", label: "Off-Grid Solar" }}
                next={{ href: "/solar-water-heater", label: "Solar Water Heater" }}
            />

            {/* Title */}
            <h1 className={styles.title}>
                On Grid Solar System For Home: Working, Subsidy, Prices, ROI & Benefits
            </h1>

            {/* Meta Information */}
            <div className={styles.meta}>
                <span>Created: August 27, 2025</span>
                <span> • Ajay</span>
                <span> • 6500 Reads</span>
                <span> • 18 mins</span>
            </div>

            <div className={styles.contentWrapper}>
                {/* Sidebar */}
                <aside className={styles.sidebar}>
                    <h3 className={styles.components}>In this article</h3>
                    <ul>
                        <li>Understanding the On-Grid Solar System</li>
                        <li>Working of On-Grid Solar System</li>
                        <li>Government Subsidy</li>
                        <li>Estimated Rooftop Solar Prices in India</li>
                        <li>Subsidy for Housing Societies</li>
                        <li>ROI on On-Grid Solar</li>
                        <li>Benefits of On-Grid Solar</li>
                        <li>Conclusion</li>
                    </ul>
                </aside>

                {/* Main Content */}
                <main className={styles.mainContent}>
                    <div className={styles.imageWrapper}>
                        <Image
                            src="/images/Ongrid.png"
                            alt="On-Grid Solar Line Diagram"
                            width={500}
                            height={300}
                            className={styles.image}
                        />
                    </div>
                    <h2 className={styles.components}>Power Your Home with the Sun: A Comprehensive Guide to On-Grid Solar Systems in India</h2>
                    <p>
                        Harnessing the sun&#39;s energy with a rooftop on-grid solar system is an increasingly popular
                        and economically savvy choice for Indian homeowners. With rising electricity tariffs and
                        attractive government incentives, switching to solar not only contributes to a greener
                        environment but also promises significant long-term savings. This guide delves into the
                        prices, subsidies, return on investment (ROI), and working principles of on-grid solar
                        systems for homes in India.
                    </p>

                    <h2 className={styles.components}>Understanding the On-Grid Solar System</h2>
                    <p>
                        An on-grid solar system, also known as a grid-tied system, is a solar power generation
                        setup that is connected to the local utility grid. Here’s a simple breakdown of how it works:
                    </p>
                    <ul>
                        <li><strong>Solar Panels:</strong> Capture sunlight and convert it into Direct Current (DC) electricity.</li>
                        <li><strong>Solar Inverter:</strong> Converts DC electricity into AC electricity for household use.</li>
                        <li><strong>Net Meter:</strong> Records both imported and exported electricity.</li>
                        <li><strong>Grid Connection:</strong> Synchronizes with the local electricity grid.</li>
                    </ul>
                    <p>
                        During the day, your home first uses the electricity generated by the solar panels. If the
                        generation is more than your consumption, the surplus power is exported to the grid. At night
                        or on cloudy days, when solar generation is low, your home seamlessly draws the required
                        electricity from the grid. This two-way flow of electricity is managed by the net meter.
                    </p>

                

                    <h2 className={styles.components}>The Working of an On-Grid Solar System for Home</h2>
                    <div className={styles.imageWrapper}>
                        <Image
                            src="/images/Ongrid_linediagram.jpg"
                            alt="On-Grid Solar Line Diagram"
                            width={500}
                            height={300}
                            className={styles.image}
                        />
                    </div>
                    <ol>
                        <li>Solar panels absorb sunlight and convert it into DC.</li>
                        <li>The DC goes into the inverter that converts it into AC.</li>
                        <li>The AC is fed into a bi-directional meter.</li>
                        <li>The meter supplies AC power to your home appliances.</li>
                        <li>Excess electricity is exported to the grid.</li>
                        <li>At night, electricity is imported back from the grid.</li>
                    </ol>
                    <p>
                        This exchange is called <strong>net metering</strong>.
                    </p>

                    <h2 className={styles.components}>PM Surya Ghar: Muft Bijli Yojana (2025)</h2>
                    <p>This flagship scheme provides substantial financial assistance for residential rooftop solar installations. Under this scheme<br />
                        For 1kW      -₹30,000<br />
                        For 2kW      -₹60,000<br />
                        3 kW to 10kW- ₹78,000</p>

                    <h2 className={styles.components}>Estimated Rooftop Solar Prices in India (2025)</h2>
                    <p>The cost of a residential rooftop solar system depends on its capacity, the quality of components, and the installer. Before applying the subsidy, you can expect the approximate price range to be:<br />
                        * 1 kW System: ₹50,000 to ₹70,000<br />
                        * 2 kW System: ₹1,10,000 to ₹1,60,000<br />
                        * 3 kW System: ₹1,90,000 to ₹2,50,000<br />
                        * 5 kW System: ₹2,70,000 to ₹3,60,000</p>

                    <p> Note: These prices are indicative and may vary. It&#39;s always best to get quotes from multiple reputable installers.</p>

                    <h2 className={styles.components}>Subsidy for Housing Societies</h2>
                    <p>
                       Under the PM Surya Ghar Muft Bijli Yojana, RWAs or housing societies can get subsidy up to ₹18,000/kW fro common facilities usage (up to 500kW).
                    </p>

                    <h2 className={styles.components}>ROI on the On-Grid Solar System, India</h2>
                    <p>
                        ROI depends on panel type, sunlight received, and discovered rates in your state.
                    </p>
                    <ul>
                        <li><strong>System Cost:</strong> ₹2,80,000 (after subsidy)</li>
                        <li><strong>Electricity Tariff:</strong> ₹8 per unit</li>
                        <li><strong>Monthly Consumption:</strong> 580–600 units</li>
                        <li><strong>Generation:</strong> 580–600 units/month</li>
                        <li><strong>Break-even point:</strong> 4–5 years.</li>
                            <li><strong>Total Savings:</strong> ₹11–12 lakh in 20 years.</li>
                    </ul>

                    <h2 className={styles.components}>Benefits of Installing On-Grid Solar</h2>
                    <ul>
                        <li>Easy to track electricity generation.</li>
                        <li>Understandable solar electricity bills.</li>
                        <li>Free solar electricity after break-even (20+ years).</li>
                        <li>Huge reduction in monthly bills.</li>
                        <li>No batteries required (grid acts as storage).</li>
                        <li>No replacement costs for batteries.</li>
                        <li>Most affordable solar system type.</li>
                        <li>Subsidy available only for on-grid systems.</li>
                    </ul>

                    <h2 className={styles.components}>Conclusion</h2>
                    <p>
                        On-grid solar systems are the best option for Indian households due to affordability,
                        government subsidies, and long-term savings. By switching today, you can ensure energy
                        independence and financial stability for decades.
                    </p>
                </main>
            </div>
        </div>
    );
};

export default OnGridSolar;
